# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pummel}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Colin Shea"]
  s.date = %q{2010-02-16}
  s.description = %q{Given an RSS feed, make a tumblr-like site out of it. Uses Sinatra & Rack, inspired by Dumble.}
  s.email = %q{colin@evaryont.me}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "config.ru",
     "public/body.png",
     "public/favicon.ico",
     "public/style.css",
     "pummel.gemspec",
     "pummel.rb",
     "templates/index.erb",
     "vendor/ruby-oembed/idea.rb",
     "vendor/ruby-oembed/lib/oembed.rb",
     "vendor/ruby-oembed/lib/oembed/errors.rb",
     "vendor/ruby-oembed/lib/oembed/formatters.rb",
     "vendor/ruby-oembed/lib/oembed/provider.rb",
     "vendor/ruby-oembed/lib/oembed/provider_discovery.rb",
     "vendor/ruby-oembed/lib/oembed/providers.rb",
     "vendor/ruby-oembed/lib/oembed/response.rb",
     "vendor/ruby-oembed/lib/oembed/response/link.rb",
     "vendor/ruby-oembed/lib/oembed/response/photo.rb",
     "vendor/ruby-oembed/lib/oembed/response/rich.rb",
     "vendor/ruby-oembed/lib/oembed/response/video.rb",
     "vendor/ruby-oembed/spec/provider_spec.rb",
     "vendor/ruby-oembed/spec/providers_spec.rb",
     "vendor/ruby-oembed/spec/response_spec.rb",
     "vendor/ruby-oembed/spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/evaryont/pummel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Auto-tumble your RSS feed!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

